config/routes.rb
Rails.application.routes.draw do

  root                 'application#index'
  get    'signup'   => 'users#new'
  get    'login'    => 'sessions#new'
  #TODO Refactor days to its own REST resource
  get    'set_days' => 'users#set_days'
  post   'set_days' => 'users#update_days'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  resources :users
  resources :account_activations,  only: [:edit]
  resources :password_resets,      only: [:edit, :new, :create, :update]
  resources :lessons,              only: [:new, :create, :show, :index, :update] do
    resources :goals,              only: :update
  end
  resources :schools,              only: [:create, :index, :show, :update]
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  attr_accessor :activation_token, :reset_token, :remember_token

  field :name,              type: String
  field :email,             type: String
  field :password_digest,   type: String
  field :remember_digest,   type: String
  field :reset_digest,      type: String
  field :activation_digest, type: String
  field :admin,             type: Boolean, default: ->{ false }
  field :activated,         type: Boolean, default: ->{ false }
  field :activated_at,      type: DateTime
  field :reset_sent_at,     type: DateTime
  field :monday,            type: Boolean
  field :tuesday,           type: Boolean
  field :wednesday,         type: Boolean
  field :thursday,          type: Boolean
  field :friday,            type: Boolean
  field :phone,             type: String

  has_secure_password

  has_and_belongs_to_many :lessons
  has_many :goals

  before_save :downcase_email

  VALID_EMAIL_REGEX = /\A[\w\-\.]+@[\w\-\.]+\.\w+\z/i
  validates :name,     length: { minimum: 6, maximum: 50 },
                       presence: true,
                       uniqueness: true,
                       case_sensitive: false
  validates :email,    length: { maximum: 255, allow_blank: false },
                       format: { with: VALID_EMAIL_REGEX },
                       uniqueness: true,
                       presence: true,
                       case_sensitive: false
  validates :password, presence: true,
                       length: { minimum: 6 },
                       on: :create
  validates :password, allow_blank: true,
                       length: { minimum: 6 },
                       format: { with: /\A\S+\z/i }
  validates :phone,    presence: true,
                       format: { with: /\d{10}/ },
                       uniqueness: true

  validate do
    check_admin_email
    non_blank_password
  end


  scope :mentor, -> { where(admin: false) }

  def first_name
    self.name.split[0]
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def to_s
    email + ": " + name
  end

  def schools
    @schools ||= School.in(id: lessons.pluck(:school_id))
  end

  def lessons
    Lesson.where(user_ids: id)
  end

  private
  # validates admin emails using the debatemate_email method
  def check_admin_email
    if admin? && !debatemate_email?
      errors.add(:email, "must be hosted at debatemate.com for admin users")
    end
  end

  #non-blank password
  def non_blank_password
    unless password.nil? || password.present?
      errors.add(:password, "cannot be blank")
    end
  end

  # is this user's email hosted on debatemate.com?
  def debatemate_email?
    len = email.length
    email[(len - 15)..(len)] == "@debatemate.com"
  end

  # turns the email into all lower case
  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :force_same_user_or_admin, only: :show
  before_action :force_admin,              only: [:index, :set_days]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save && UserActivatorService.new(@user).begin
      flash[:info] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    puts @user.name
    render "show"
  end

  def index
    @users = User.mentor.order(:name.asc)
  end

  def set_days
    @users = User.mentor.order(:name.asc)
  end

  def update_days
    User.all.each do |user|
      id_key = user.id.to_s
      days = params["days"][id_key]
      if days
        day_options = %w( monday tuesday wednesday thursday friday )
        day_options.each do |day|
          user.update_attribute(day, days[day] == true)
        end
      end
    end
    flash[:success] = "Days updated"
    redirect_to root_url
  end

  private

  def user_params
    params[:admin] = params[:admin] == "1"
    params.require(:user).permit(:password, :password_confirmation,
                                 :name,     :email,
                                 :admin,    :monday,
                                 :tuesday,  :wednesday,
                                 :thursday, :friday,
                                 :phone)
  end

  # Forces the current_user to be logged in and either an admin or the user
  # whose profile is being shown
  def force_same_user_or_admin
    unless admin? || (current_user && current_user.id == params[:id])
      flash[:danger] = if logged_in?
                         "You cannot view other users' profiles"
                       else
                         "You must be logged in to view this page"
                       end
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_set_days_row.html.erb
<div class="row">
  <div class="col-md-3">
    <span><%= user.name %></span>
  </div>
  <div class="col-md-9">
    <%= f.fields_for user.name do |user_form| %>
      <table class="days-table">
        <tr>
          <td>M</td>
          <td>Tu</td>
          <td>W</td>
          <td>Th</td>
          <td>F</td>
        </tr>
        <tr>
          <td><%= user_form.check_box :monday, {}, true, false %></td>
          <td><%= user_form.check_box :tuesday, {}, true, false %></td>
          <td><%= user_form.check_box :wednesday, {}, true, false %></td>
          <td><%= user_form.check_box :thursday, {}, true, false %></td>
          <td><%= user_form.check_box :friday, {}, true, false %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<% cache user do %>
  <div class="user">
    <%= link_to user.name, user %>
  </div>
<% end %>

app/views/users/_user_form.html.erb
<%= render 'shared/error_messages', object: @user %>

<%= form_for @user, html: { id: "user" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>

  <%= f.label :phone, "Phone number" %>
  <%= f.phone_field :phone, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.label :admin, "Admin account?" %>
  <%= f.check_box :admin, id: "admin" %><br>

  <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>

<h1>Users</h1>

<h4>
  <%= link_to "Set days", set_days_path %>
</h4>

<%= render @users %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Sign up</h1>
    <%= render 'user_form' %>
  </div>
</div>

app/views/users/set_days.html.erb
<h1>Set Days</h1>
<%= form_tag set_days_path, method: :post do %>
  <% @users.each do |user| %>
    <div class="row">
      <div class="col-md-3">
        <span><%= user.name %></span>
      </div>
      <div class="col-md-9">
        <table class="days-table">
          <tr>
            <td>M</td>
            <td>Tu</td>
            <td>W</td>
            <td>Th</td>
            <td>F</td>
          </tr>
          <tr>
            <td><%= check_box_tag "days[#{user.id}][monday]", true,
            user.monday %></td>
            <td><%= check_box_tag "days[#{user.id}][tuesday]", true,
            user.tuesday %></td>
            <td><%= check_box_tag "days[#{user.id}][wednesday]", true,
            user.wednesday %></td>
            <td><%= check_box_tag "days[#{user.id}][thursday]", true,
            user.thursday %></td>
            <td><%= check_box_tag "days[#{user.id}][friday]", true,
            user.friday %></td>
          </tr>
        </table>
      </div>
    </div>
  <% end %>
  <%= submit_tag "Save", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %></h1>

<h4><%= link_to @user.email, "mailto:#{@user.email}" %></h4>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">Completed Lessons</div>
      <div class="panel-body">
        <ul>
          <% @user.lessons.completed.each do |lesson| %>
            <li><%= link_to lesson.to_s, lesson %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">Upcoming Lessons</div>
      <div class="panel-body">
        <ul>
          <% @user.lessons.upcoming.each do |lesson| %>
            <li><%= link_to lesson.to_s, lesson %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>