config/routes.rb
Rails.application.routes.draw do

  root                 'application#index'
  get    'signup'   => 'users#new'
  get    'login'    => 'sessions#new'
  #TODO Refactor days to its own REST resource
  get    'set_days' => 'users#set_days'
  post   'set_days' => 'users#update_days'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  resources :users
  resources :account_activations,  only: [:edit]
  resources :password_resets,      only: [:edit, :new, :create, :update]
  resources :lessons,              only: [:new, :create, :show, :index, :update] do
    resources :goals,              only: :update
  end
  resources :schools,              only: [:create, :index, :show, :update]
end

app/models/lesson.rb
class Lesson
  include Mongoid::Document

  field :date, type: Date

  belongs_to :school
  has_many :goals
  has_and_belongs_to_many :users

  validates_presence_of :date

  accepts_nested_attributes_for :goals

  scope :upcoming, ->{ where(:date.gte => Date.today).order(:date.asc) }
  scope :completed, ->{ where(:date.lt => Date.today).order(:date.desc) }

  def given_by?(user)
    self.users.map(&:id).include?(user.id)
  end

  def to_s
    date.to_formatted_s(:short) + ": " + school.name
  end

  def delete_goals
    goals.each { |goal| goal.destroy unless users_ids.include? goal.user_id }
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  include LessonsHelper
  include SessionsHelper
  before_action :force_login
  before_action :force_same_user_or_admin, only: :show

  def new
    @user   = current_user
    @lesson = Lesson.new
    @lesson.goals.build
    @school_options = School.all.map { |s| [s.name, s.id] }
  end

  def create
    find_or_initialize_lesson
    if !@lesson.new_record? && @lesson.given_by?(current_user)
      flash[:danger]  = "You have already created a lesson on the same day "
      flash[:danger] += "at the same school"
      redirect_to @lesson
      return
    end
    goal = Goal.new(lesson_params[:goals_attributes]['0'])
    @lesson.goals << goal
    if @lesson.save
      flash[:success] = "Response logged"
      redirect_to @lesson
    else
      @user = current_user
      @school_options = School.all.map { |s| [s.name, s.id] }
      render 'new'
    end
  end

  def index
    admin? ? lessons = Lesson.all : lessons = current_user.lessons
    @upcoming_lessons  = lessons.upcoming
    @completed_lessons = lessons.order(date: 'desc').completed
  end

  def update
    @lesson = Lesson.find(lesson_params[:id])
    if @lesson.update_attributes(lesson_params)
      flash[:success] = "Changes successful"
      if @lesson.users.any?
        @lesson.delete_goals
        redirect_to @lesson
      else
        @lesson.destroy
        flash[:info] = "No other mentors for that lesson. Lesson deleted."
        redirect_to root_path
      end
    else
      flash[:danger] = "Changes unsuccessful. See the link in the footer to"
      flash[:danger] += "contact the developer if problems persist"
      redirect_to @lesson
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
    @message =  "Are you sure? Only do this if you and the other "
    @message += "mentors in this lesson are chaning the date. Otherwise, remove"
    @message += " yourself from this lesson and create a new one."
  end

  private

    # Forces the current_user to be logged in and either an admin or the user
    # whose profile is being shown
    def force_same_user_or_admin
      @lesson = Lesson.find(params[:id])
      force_redirect_unless do
        admin? || (current_user && @lesson.given_by?(current_user))
      end
    end

    # strong params
    def lesson_params
      params.require(:lesson).permit(:id, :school_id, :date, :user_id,
                                     goals_attributes: [:id, :text,
                                                        :lesson_id, :user_id])
    end

    # Finds a lesson with the same date and school, or creates the lesson
    def find_or_initialize_lesson
      @lesson = Lesson.find_or_initialize_by(
        date: lesson_params[:date],
        school_id: lesson_params[:school_id]
      )
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper

  def delete_or_redirect_home(object, success_message = "Deletion successful")
    error_message  = "An error occurred. Try again. See the link in the "
    error_message += "footer to report a bug if the problem persists"
    if object.destroy
      flash[:success] = success_message
    else
      flash[:danger] = error_message
    end
    redirect_to root_url
  end

  def row_name(lesson, mentor)
    names = mentor.admin? ? " (#{mentor_list(lesson)})" : ''
    mentor.to_s + names
  end

  def mentor_list(lesson)
    lesson.users.map(&:name).join(", ")
  end

end

app/views/lessons/_date_change_modal.html.erb
<div class="modal fade" id="dateModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <a type="button" class="close" data-dismiss="modal"
        aria-label="Close"><span aria-hidden="true">&times;</span></a>
        <h4 class="modal-title">Change date</h4>
      </div>
      <%= form_for @lesson do |f| %>

        <%= f.hidden_field :id, value: @lesson.id %>

        <div class="modal-body">
          <%= f.label :date %>
          <%= f.date_field :date %>
        </div>

        <div class="modal-footer">
          <a type="button" class="btn btn-default"
          data-dismiss="modal">Close</a>
          <%= f.submit "Save changes",
          class: "btn btn-primary", data: { confirm: @message } %>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/lessons/_goal.html.erb
<li>
  <div class="show-goal">
    <%= goal.text %>
    -<%= goal.user.name %>
    <% if current_user.id == goal.user_id %>
      <%= link_to "(edit)", '#', id: "edit-goal-button" %>
    <% end %>
  </div>
  <div class="edit-goal">
    <%= form_for goal, url: lesson_goal_path(lesson_id: @lesson.id, id: goal.id),
                       method: :patch do |f| %>
      <%= f.hidden_field :user_id, value: goal.user_id %>

      <%= f.text_area :text, class: "form-control" %>

      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>
</li>

app/views/lessons/_lesson.html.erb
<% cache lesson do %>
  <div class="lesson">
    <%= link_to row_name(lesson, current_user), lesson %>
  </div>
<% end %>

app/views/lessons/index.html.erb
<% provide(:title, "Lessons") %>

<h1>Lessons</h1>
<% if !admin? %>
  <center>
    <%= link_to "Plan a Lesson", new_lesson_path,
                                 class: "btn btn-primary btn-center" %>
  </center>
<% end %>
<div class="row">
  <div class="col-md-6">
    <h2>Upcoming</h2>
    <% @upcoming_lessons.each do |lesson| %>
      <%= render 'lesson', lesson: lesson %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2>Completed</h2>
    <% @completed_lessons.each do |lesson| %>
      <%= render 'lesson', lesson: lesson %>
    <% end %>
  </div>
</div>

app/views/lessons/new.html.erb
<% provide(:title, "New Lesson") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Pre Lesson Survey</h1>

    <%= render 'shared/error_messages', object: @lesson %>

    <%= form_for @lesson do |f| %>
      <%= f.hidden_field :user_id, value: @user.id %>

      <%= f.label :school %><br>
      <%= f.select :school_id, @school_options %><br>

      <%= f.label :date, "Date planned for lesson" %><br>
      <%= f.date_field :date %><br>

      <%= f.fields_for :goals do |response_form| %>
        <%= response_form.hidden_field :user_id, value: @user.id %>

        <%= response_form.label :text, "Goals for this lesson" %>
        <%= response_form.text_area :text, class: "form-control" %>
      <% end %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lessons/show.html.erb
<% provide(:title, @lesson.to_s) %>

<h1><%= @lesson.to_s %></h1>
<h4>Mentor<%= "s" if @lesson.users.count > 1 %>:
  <% if admin? %>
    <% @lesson.users.each_with_index do |user, index| %>
      <%= link_to user.name, user %>
      <%= ", " unless @lesson.users.count - 1 == index %>
    <% end %>
  <% else %>
    <%= mentor_list(@lesson) %>
  <% end %></h4>

<center>

  <%= form_for @lesson, html: {id: "remove_me_data"} do |f| %>
    <%= f.hidden_field :user_ids, value: @lesson.user_ids - [current_user.id] %>
  <% end %>

  <%= link_to "Remove me from this lesson", '#',
               data: { confirm: "Are you sure?"} %> |
  <%= link_to "Change the date of this lesson", '#', id: "date-change-button",
              data: { toggle: "modal",
                      target: "#dateModal" } %>
</center>

<%= render 'date_change_modal' %>

<h3>Goals</h3>
<ul>
  <% @lesson.goals.each do |goal| %>
    <%= render 'goal', goal: goal %>
  <% end %>
</ul>