config/routes.rb
Rails.application.routes.draw do

  root                 'application#index'
  get    'signup'   => 'users#new'
  get    'login'    => 'sessions#new'
  #TODO Refactor days to its own REST resource
  get    'set_days' => 'users#set_days'
  post   'set_days' => 'users#update_days'
  post   'login'    => 'sessions#create'
  delete 'logout'   => 'sessions#destroy'

  resources :users
  resources :account_activations,  only: [:edit]
  resources :password_resets,      only: [:edit, :new, :create, :update]
  resources :lessons,              only: [:new, :create, :show, :index, :update] do
    resources :goals,              only: :update
  end
  resources :schools,              only: [:create, :index, :show, :update]
end

app/views/layouts/_admin_header.html.erb
<%= link_to "Lessons", lessons_path %>
<%= link_to "Users", users_path %>
<%= link_to "Schools", schools_path %>
<%= link_to "Log out", logout_path, method: :delete %>

app/views/layouts/_footer.html.erb
<div class="row">
  <footer>
    <center>
      <small><%= link_to "Contribute to this project on GitHub",
                         "https://github.com/BenMusch/debatemate-admin",
                         target: "_blank" %>     |     
            <%= link_to "Report a bug or request a feature",
                         "mailto:muschol.b@husky.neu.edu" %></small>
      <%= debug(params) if Rails.env.development? %>
    </center>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar navbar-header">
      <%= link_to "Debate Mate USA", root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar navbar-right">
      <% if admin? %>
        <%= render 'layouts/admin_header' %>
      <% elsif logged_in? %>
        <%= render 'layouts/user_header' %>
      <% else %>
        <%= render 'layouts/unregistered_header' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_user_header.html.erb
<%= link_to "Log out", logout_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>